import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "../../components/navbar";
import { LandingSection } from "../../components/landing";
import Products from "../../components/products";
import { Footer } from "../../components/footer";

const inter = Inter({ subsets: ["latin"] });

export default function ProductPage() {
  return (
    <>
      <Head>
        <title>Prooducts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Products />
      <Products />
      <Products />
      <Footer />
    </>
  );
}
